version: 2

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  govet:
    disable-all: true
    enable:
      - atomic
      - bools
      - composites
      - copylocks
      - nilfunc
      - stdmethods
      - structtag

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
